apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  namespace: scraper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
        - name: scraper
          image: <registry>/scraper-scraper:latest
          envFrom:
            - configMapRef:
                name: scraper-config
            - secretRef:
                name: scraper-secrets
