apiVersion: v1
kind: Secret
metadata:
  name: scraper-secrets
  namespace: scraper
type: Opaque
stringData:
  DATABASE_URL: "postgresql://scraper:scraper@postgres:5432/scraper"
  POSTGRES_PASSWORD: "scraper"
  # PROXY_URL: "http://user:pass@proxy.example.com:8080"
